In [1]:
import numpy as np


---
$OUTPUT = \sigma(w^Tx + b)$   
Now, u are done with foreward pass,   

Find a way how to implement backpropagation

In [2]:
from NeuralNet import relu
from NeuralNet import NN

In [3]:
Net = NN(3)

In [4]:
Net.add_layer(3)

In [5]:
Net.add_layer(3)

In [6]:
Net.add_layer(2)

In [7]:
Net.predict(np.array([1,2,3]))

array([ 2.53155268, -0.00674331])

In [8]:
np.array([1,2,4])**2

array([ 1,  4, 16])

In [9]:
Net.error([1.0])

np.float64(1.6795928534781868)

In [10]:
Net.backward_pass([2.5, -1])

first Sigma:
[0.03155268 0.00993257]
W:
, [[ 0.35586187  1.29155568  0.50709904]
 [ 0.60728755 -1.62649688  0.26946376]]
[0.03155268 0.00993257]
W:
, [[ 0.12052021  0.67985988  1.5145258 ]
 [ 0.06436513  0.36636568 -0.40208607]
 [ 1.37333273  0.42007378  0.51033509]]
[0.01726032 0.02459676 0.00018677]
Neuron 0: 
 old weights and bias
[0.35586187 1.29155568 0.50709904]  + b=  1.1313090496683573
gradient: [ 0.05972431  0.0177992  -0.00011994] + del b = 0.03155268304128578 
New weights + bias: [0.34988944 1.28977576 0.50711103] b_new = 1.1281537813642288
Neuron 1: 
 old weights and bias
[ 0.60728755 -1.62649688  0.26946376]  + b=  -0.9052828751276166
gradient: [ 1.88008007e-02  5.60306629e-03 -3.77571926e-05] + del b = 0.009932566930813931 
New weights + bias: [ 0.60540746 -1.62705719  0.26946754] b_new = -0.906276131820698


'Ala'