In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a[-1::-1]

array([4, 3, 2, 1])


---
$OUTPUT = \sigma(w^Tx + b)$   
Now, u are done with foreward pass,   

Find a way how to implement backpropagation

In [3]:
from NeuralNet import relu
from NeuralNet import NN

In [4]:
Net = NN(3)

In [5]:
Net.add_layer(3)

In [6]:
Net.add_layer(3)

In [7]:
Net.add_layer(2)

In [8]:
Net.predict(np.array([1,2,3]))

array([-0.00025548, -0.00822213])

In [9]:
np.array([1,2,4])**2

array([ 1,  4, 16])

In [10]:
Net.error([1.0])

np.float64(1.0085114505946269)

In [11]:
Net.backward_pass([2.5, -1])

first Sigma:
[-0.02500255  0.00991778]
W:
, [[-0.16145738  0.69968111  0.21435642]
 [-0.47479266  0.33430953  0.10679299]]
[-0.02500255  0.00991778]
W:
, [[ 0.73638146 -0.41575477 -0.14452745]
 [ 0.13699776  0.34867885 -1.3783097 ]
 [-0.29112545 -0.30708204 -3.00600039]]
[-6.72041536e-04 -1.41782074e-02 -4.30030880e-05]
Neuron 0: 
 old weights and bias
[-0.16145738  0.69968111  0.21435642]  + b=  -0.14702048357361547
gradient: [-0.10142111 -0.02787141  0.00041428] + del b = -0.02500255484855794 
New weights + bias: [-0.15131527  0.70246825  0.21431499] b_new = -0.14452022808875967
Neuron 1: 
 old weights and bias
[-0.47479266  0.33430953  0.10679299]  + b=  0.7328503399981824
gradient: [ 0.04023077  0.01105577 -0.00016433] + del b = 0.009917778686196406 
New weights + bias: [-0.47881573  0.33320395  0.10680943] b_new = 0.7318585621295628
sigma_arr
[array([-2.42474224e-03, -4.65103113e-05,  1.97683565e-04]), array([-6.72041536e-04, -1.41782074e-02, -4.30030880e-05]), array([-0.02500255,

'Ala'

In [12]:
Net.nn_layer_list[2].layer_output

array([-0.00025548, -0.00822213])

In [13]:
[1] + [1,2]

[1, 1, 2]

In [ ]:
 0.04023077,  0.01105577, -0.00016433]])]