In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a[-1::-1]

array([4, 3, 2, 1])


---
$OUTPUT = \sigma(w^Tx + b)$   
Now, u are done with foreward pass,   

Find a way how to implement backpropagation

In [3]:
from NeuralNet import leaky_relu
from NeuralNet import NN

In [4]:
Net = NN(3)

In [5]:
Net.add_layer(3)

In [6]:
Net.add_layer(3)

In [7]:
Net.add_layer(2)

In [8]:
Net.predict(np.array([1,2,3]))

array([0.95595625, 0.09355278])

In [9]:
print("Old weights: \n")
for layer in Net.nn_layer_list:
    print(layer.get_weights())
print("-------------------")

Old weights: 

[[ 0.34964003 -0.59990439 -0.52811407  1.40600926]
 [-0.69317077 -0.06619549 -1.19812079 -0.11539313]
 [-1.96726377  0.20070406 -1.28720522 -0.38470396]]
[[ 7.84687865e-02  3.32831131e-01 -3.92076778e-01 -1.21821820e+00]
 [-1.65348553e-01  4.72846214e-01  2.02746488e+00  8.73083082e-02]
 [-9.64562263e-04  2.17081789e-01  9.64385203e-01  6.82300005e-01]]
[[ 0.10700521 -0.53954381 -0.30255564  1.14348036]
 [-1.66382926  0.75103841  1.40012848 -0.78928126]]
-------------------


In [10]:
Net.error([1.0])

np.float64(0.41179320543395576)

In [11]:
Net.backward_pass([2.5, -1])

first Sigma:
[-1.54404375  1.09355278]
-------------
i (layer from last to first) 1
W:
 [[ 0.10700521 -0.53954381 -0.30255564]
 [-1.66382926  0.75103841  1.40012848]]
sig old: 
 [-1.54404375  1.09355278]
-------------
i (layer from last to first) 0
W:
 [[ 7.84687865e-02  3.32831131e-01 -3.92076778e-01]
 [-1.65348553e-01  4.72846214e-01  2.02746488e+00]
 [-9.64562263e-04  2.17081789e-01  9.64385203e-01]]
sig old: 
 [-0.01984706  0.01654379  1.99827353]
Neuron 0: 
 old weights and bias
[ 0.10700521 -0.53954381 -0.30255564]  + b=  1.1434803565093512
gradient: [ 1.87034962e-02  7.76282930e-04 -9.51768359e-01] + del b = -1.544043746200627 
New weights + bias: [ 0.10513486 -0.53962144 -0.2073788 ] b_new = 1.297884731129414
Neuron 1: 
 old weights and bias
[-1.66382926  0.75103841  1.40012848]  + b=  -0.7892812642464468
gradient: [-1.32465549e-02 -5.49794240e-04  6.74079953e-01] + del b = 1.0935527818518465 
New weights + bias: [-1.66250461  0.75109338  1.33272048] b_new = -0.8986365424316315

'Ala'

In [12]:
Net.nn_layer_list[2].layer_output

array([0.95595625, 0.09355278])

In [13]:
print("New weights: \n")
for layer in Net.nn_layer_list:
    print(layer.get_weights())
print("-------------------")

New weights: 

[[ 0.34964625 -0.59989195 -0.52809541  1.40601548]
 [-0.69360577 -0.0670655  -1.19942581 -0.11582814]
 [-1.9692322   0.1967672  -1.29311051 -0.38667239]]
[[ 7.84483738e-02  3.32741118e-01 -3.92192133e-01 -1.21623349e+00]
 [-1.65331537e-01  4.72921246e-01  2.02756103e+00  8.56539288e-02]
 [ 1.09066546e-03  2.26144593e-01  9.75999519e-01  4.82472652e-01]]
[[ 0.10513486 -0.53962144 -0.2073788   1.29788473]
 [-1.66250461  0.75109338  1.33272048 -0.89863654]]
-------------------
