In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a[-1::-1]

array([4, 3, 2, 1])


---
$OUTPUT = \sigma(w^Tx + b)$   
Now, u are done with foreward pass,   

Find a way how to implement backpropagation

In [3]:
from NeuralNet import relu
from NeuralNet import NN

In [4]:
Net = NN(3)

In [5]:
Net.add_layer(3)

In [6]:
Net.add_layer(3)

In [7]:
Net.add_layer(2)

In [8]:
Net.predict(np.array([1,2,3]))

array([2.20860817, 1.11277485])

In [9]:
np.array([1,2,4])**2

array([ 1,  4, 16])

In [10]:
Net.error([1.0])

np.float64(0.7367259333106674)

In [11]:
Net.backward_pass([2.5, -1])

first Sigma:
[-0.29139183  2.11277485]
W:
, [[ 0.09707765  0.13409911 -0.84918549]
 [ 0.58359875 -1.20836174 -0.6134728 ]]
[-0.29139183  2.11277485]
W:
, [[-1.21944154  0.56079341  1.47637741]
 [-0.28233822 -0.59794411  0.55203006]
 [-1.01852549 -1.62650619  0.34336909]]
[ 1.20472514 -0.02592072 -0.01048684]
Neuron 0: 
 old weights and bias
[ 0.09707765  0.13409911 -0.84918549]  + b=  2.0337422607319184
gradient: [-0.34349361  0.00933048  0.0222097 ] + del b = -0.2913918336626735 
New weights + bias: [ 0.13142701  0.13316606 -0.85140646] b_new = 2.0628814440981857
Neuron 1: 
 old weights and bias
[ 0.58359875 -1.20836174 -0.6134728 ]  + b=  0.33937609983512035
gradient: [ 2.49054564 -0.06765185 -0.16103434] + del b = 2.112774850405842 
New weights + bias: [ 0.33454419 -1.20159655 -0.59736937] b_new = 0.12809861479453613
sigma_arr
[array([-0.01451092,  0.70815797,  0.01760719]), array([ 1.20472514, -0.02592072, -0.01048684]), array([-0.29139183,  2.11277485])]


'Ala'

In [12]:
Net.nn_layer_list[2].layer_output

array([2.20860817, 1.11277485])

In [13]:
[1] + [1,2]

[1, 1, 2]