In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a[-1::-1]

array([4, 3, 2, 1])


---
$OUTPUT = \sigma(w^Tx + b)$   
Now, u are done with foreward pass,   

Find a way how to implement backpropagation

In [3]:
from NeuralNet import leaky_relu
from NeuralNet import NN

In [4]:
Net = NN(3)

In [5]:
Net.add_layer(3)

In [6]:
Net.add_layer(3)

In [7]:
Net.add_layer(2)

In [8]:
Net.predict(np.array([1,2,3]))

array([ 2.05335723, -0.00713438])

In [9]:
print("Old weights: \n")
for layer in Net.nn_layer_list:
    print(layer.get_weights())
print("-------------------")

Old weights: 

[[-0.54002277  0.03957457  1.11407277 -1.26402139]
 [-0.11338409  1.21430147  0.3859328   0.58810314]
 [ 0.18790445  1.16775793 -0.20480472  0.53255805]]
[[-1.1400851   0.45861426 -1.90181799 -0.77627024]
 [ 1.05571877 -0.99681489 -1.46905369  1.24119774]
 [ 2.57088748 -1.31270537  0.44421615  0.77825798]]
[[-0.2024243   1.42461721  1.14469681  1.31964121]
 [ 1.19976401 -0.86451899  0.14277702 -0.78763086]]
-------------------


In [10]:
Net.error([1.0])

np.float64(1.0619405533020219)

In [11]:
Net.backward_pass([2.5, -1])

first Sigma:
[-0.44664277  0.00992866]
-------------
i (layer from last to first) 1
W:
 [[-0.2024243   1.42461721  1.14469681]
 [ 1.19976401 -0.86451899  0.14277702]]
sig old: 
 [-0.44664277  0.00992866]
-------------
i (layer from last to first) 0
W:
 [[-1.1400851   0.45861426 -1.90181799]
 [ 1.05571877 -0.99681489 -1.46905369]
 [ 2.57088748 -1.31270537  0.44421615]]
sig old: 
 [ 0.00102323 -0.00644878 -0.50985297]


AttributeError: 'Layer' object has no attribute 'nr_neurons'

In [ ]:
Net.nn_layer_list[2].layer_output

In [ ]:
print("New weights: \n")
for layer in Net.nn_layer_list:
    print(layer.get_weights())
print("-------------------")